import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/navbar";
import Footer from "./_components/footer/footer";
import { Toaster } from "./_components/ui/sonner";
import { cookies } from "next/headers";
import { supabase } from "@/lib/supabase/server";
import { prisma } from "@/lib/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get access token from cookie
  const cookieStore = await cookies();
  const token = cookieStore.get("auth-token")?.value;

  let currentUser: { name: string | null; role: "CUSTOMER" | "SALON"; salonId?: number } | null =
    null;

  if (token) {
    const { data: authData } = await supabase.auth.getUser(token);
    const authUser = authData?.user;

    if (authUser) {
      const dbUser = await prisma.user.findUnique({
        where: { id: authUser.id },
        include: {
          salon: true,
        },
      });

      if (dbUser) {
        currentUser = {
          name: dbUser.name ?? null,
          role: dbUser.role as "CUSTOMER" | "SALON",
          salonId: dbUser.salon?.id,
        };
      }
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar currentUser={currentUser} />
          {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
